article/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    path('new_article/', views.new_article, name='new_article'),
]

discussion_board_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls')),
    path('users/', include('users.urls'))
]

users/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views

app_name = "users"

urlpatterns = [
    # path('', include('django.contrib.auth.urls'))
    url(r'^login/$', LoginView.as_view(template_name= 'users/login.html'),
        name='login'),
        
    # Logout page.
    url(r'^logout/$', views.logout_view, name='logout'),

    url('register/', views.register, name='register')
]

article/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    """the content of a article"""
    authors = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='用户')
    title = models.CharField(max_length=200)
    content = models.TextField()
    click_nums = models.IntegerField(default=0,verbose_name='阅读数量')
    is_deleted = models.BooleanField(default=False,verbose_name='是否删除')
    created_time = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'atricles'
 
    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.content[:50]}..."

users/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['content']
        labels = {'content': 'Content:'}
        widgets = {'content': forms.Textarea(attrs={'cols': 80})}

article/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import ArticleForm
from .models import Article

# Create your views here.

def index(request):
    articles = Article.objects.order_by('created_time')
    return render(request, 'index.html', {'articles':articles})

@login_required
def new_article(request):

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = ArticleForm()
    else:
        # POST data submitted; process data.
        form = ArticleForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.authors = User.objects.first()
            new_entry.save()
            return redirect('article:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'article/new_article.html', context)

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render
from django.contrib.auth import logout, login

# Create your views here.
def logout_view(request):
    """Log the user out."""
    logout(request)
    return render(request, 'index.html')


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('article:index')

    context = {'form':form}
    return render(request, 'users/register.html', context)

templates/article/new_article.html
{% extends 'base.html' %}
{% block content %}

  <p>Add a new article:</p>
  <form action="{% url 'article:new_article' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class="btn btn-primary">Add article</button>
  </form>

{% endblock content %}

templates/base.html
{% load bootstrap4 %}

<!doctype html>
<html>
<head>
<title>Discussion Board</title>

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
</head>

<body>
<h1>
Welcome to Discussion Board
</h1>

{% if user.is_authenticated %}
  <p>hello, {{user.username}} </p>
{% else %}
  <p>hello, guest!</p>
{% endif %}

{% block content %}
{% endblock content %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<p>Welcome</p>

{% if user.is_authenticated %}
    <ul>
    {% for article in articles %}
        <li>{{article}}</li>
    {% empty %}
        <li>No articles</li>
    {% endfor %}
    </ul>
    <div>
    <a href="{% url 'article:new_article' %}">Add a new article</a>
    </div>
    <div>
        <a href="{% url 'users:logout' %}">log out</a>
    </div>
{% else %}
<div>
    <a href="{% url 'users:login' %}">Log in</a>
<div>
<div>
    <a href="{% url 'users:register' %}">Register</a>
<div>
{% endif %}


{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    {% if form.errors %}
        <p>Your name and password didn't work</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{form.as_p}}

        <button name="submit">Log in</button>
        <input type="hidden" name="next" value="{% url 'article:index' %}" />
    </form>
{% endblock content %}

templates/users/register.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}" >
        {% csrf_token %}
        {{form.as_p}}
        <button name="submit">Register</button>
        <input type="hidden" name="next" value="{% url 'article:index' %}" />
    </form>
{% endblock content %}